public class NonDenotableExample {
    public static void main(String[] args) {
        // Demonstrating "non-denotable types" using var.
        // These are types that are legal in Java but cannot be written explicitly 
        // as the type of a variable. They must be inferred.

        // The variable 'duck' has an unusual type - it is effectively Object 
        // but extended with a method called quack().
        // We create an anonymous class here.
        var duck = new Object() {
            public void quack() {
                System.out.println("Quack! I am a non-denotable type.");
            }
        };

        // With LVTI (Local Variable Type Inference), we can use the inferred type.
        // This allows us to call quack(), which wouldn't be possible if we declared
        // the variable as 'Object duck'.
        duck.quack();

        // The actual type name is generated by the compiler and is not usable in source code.
        // This is a glimpse of "structural typing" or "duck typing" in Java.
        System.out.println("Inferred type class: " + duck.getClass().getName());
    }
}